[package]
name = "merix-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Unified API for db + cache"
rust-version.workspace = true

[dependencies]
merix-core = { workspace = true }
merix-db = { workspace = true }
merix-cache = { workspace = true }